server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location /crm/ {
        try_files $uri $uri/ /crm/index.html;
    }

    location /dashboard/ {
        try_files $uri $uri/ /dashboard/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
