import {
  defaultCompany,
  defaultHistoricalInputs,
  defaultInputs,
} from './financeModel';

export const companyFields = [
  { key: 'companyName', label: 'Entreprise', type: 'text' },
  { key: 'sector', label: 'Secteur', type: 'text' },
  { key: 'currency', label: 'Devise groupe', type: 'text' },
  { key: 'accountingFramework', label: 'Referentiel', type: 'text' },
];

export const marketFields = [
  { key: 'totalMarketSize', label: 'Marche dermatologie USA (kUSD)', type: 'number' },
  { key: 'dermatologyShare', label: 'Part du segment cible (%)', type: 'number' },
  { key: 'genericShare', label: 'Part generiques du segment (%)', type: 'number' },
  { key: 'marketGrowthRate', label: 'Croissance annuelle du marche (%)', type: 'number' },
  { key: 'addressableShare', label: 'Part reellement accessible (%)', type: 'number' },
  { key: 'targetShare', label: 'Part de marche cible a maturite (%)', type: 'number' },
  {
    key: 'averagePricePerTreatment',
    label: 'Prix moyen par traitement (USD)',
    type: 'number',
  },
  { key: 'competitorCount', label: 'Nombre de concurrents clefs', type: 'number' },
  { key: 'regulatoryLeadMonths', label: 'Lead time reglementaire (mois)', type: 'number' },
];

export const projectFields = [
  { key: 'projectName', label: 'Projet', type: 'text' },
  { key: 'currency', label: 'Devise projet', type: 'text' },
  { key: 'discountRate', label: 'Taux d actualisation (%)', type: 'number' },
  { key: 'taxRate', label: 'Taux d impot (%)', type: 'number' },
  { key: 'workingCapitalRate', label: 'BFR cible (% du CA)', type: 'number' },
  { key: 'initialWorkingCapital', label: 'BFR initial (kUSD)', type: 'number' },
  { key: 'timeToMarketMonths', label: 'Time to market (mois)', type: 'number' },
  { key: 'decisionDeadline', label: 'Decision attendue', type: 'text' },
  { key: 'sponsor', label: 'Sponsor interne', type: 'text' },
];

export const yearlyProjectFieldGroups = [
  {
    title: 'Revenus projetes',
    key: 'revenueByYear',
    prefix: 'Revenus ',
  },
  {
    title: 'Marge EBITDA',
    key: 'ebitdaMarginByYear',
    prefix: 'Marge ',
    suffix: ' %',
  },
  {
    title: 'CAPEX',
    key: 'capexByYear',
    prefix: 'Capex ',
  },
  {
    title: 'Depreciation',
    key: 'depreciationByYear',
    prefix: 'Amort. ',
  },
  {
    title: 'Frais fixes de lancement',
    key: 'fixedCostsByYear',
    prefix: 'Frais ',
  },
];

export const scenarioFields = [
  { key: 'revenueMultiplier', label: 'Multiplicateur CA', type: 'number', step: '0.01' },
  { key: 'marginMultiplier', label: 'Multiplicateur marge', type: 'number', step: '0.01' },
  { key: 'opexMultiplier', label: 'Multiplicateur opex', type: 'number', step: '0.01' },
  { key: 'capexMultiplier', label: 'Multiplicateur capex', type: 'number', step: '0.01' },
  {
    key: 'workingCapitalMultiplier',
    label: 'Multiplicateur BFR',
    type: 'number',
    step: '0.01',
  },
];

export const historicalSections = [
  {
    title: 'Compte de resultat',
    subtitle: 'Vision comparee du groupe sur plusieurs exercices.',
    fields: [
      { key: 'revenue', label: "Chiffre d'affaires" },
      { key: 'purchases', label: 'Achats / couts directs' },
      { key: 'personnelExpenses', label: 'Charges de personnel' },
      { key: 'otherOperatingExpenses', label: "Autres charges d'exploitation" },
      { key: 'depreciation', label: 'Amortissements' },
      { key: 'financialResult', label: 'Resultat financier' },
      { key: 'taxExpense', label: 'Charge fiscale' },
      { key: 'nonRecurringItems', label: 'Elements non recurrents' },
    ],
  },
  {
    title: 'Bilan et cycle',
    subtitle: 'Base de lecture structurelle et besoins de financement.',
    fields: [
      { key: 'inventory', label: 'Stocks' },
      { key: 'receivables', label: 'Creances et comptes transitoires' },
      { key: 'cash', label: 'Liquidites' },
      { key: 'fixedAssets', label: 'Immobilisations' },
      { key: 'equity', label: 'Capitaux propres' },
      { key: 'longTermDebt', label: 'Dettes financieres long terme' },
      { key: 'shortTermFinancialDebt', label: 'Dettes financieres court terme' },
      { key: 'suppliers', label: 'Dettes fournisseurs' },
      { key: 'otherOperatingLiabilities', label: "Autres dettes d'exploitation" },
      { key: 'previousBfr', label: 'BFR periode precedente' },
      { key: 'openingCash', label: "Tresorerie d'ouverture" },
    ],
  },
  {
    title: 'Flux et retraitements',
    subtitle: 'Pont entre performance, cash et financement.',
    fields: [
      { key: 'capex', label: 'Investissements (CAPEX)' },
      { key: 'assetDisposals', label: "Cessions d'actifs" },
      { key: 'newLongTermDebt', label: 'Nouveaux emprunts LT' },
      { key: 'debtRepayment', label: "Remboursements d'emprunts" },
      { key: 'capitalIncrease', label: 'Augmentation de capital' },
      { key: 'dividends', label: 'Dividendes verses' },
      { key: 'latentReserves', label: 'Variation reserves latentes' },
      { key: 'otherNonCashAdjustments', label: 'Autres ajustements non cash' },
    ],
  },
];

export const mandateCatalog = [
  {
    id: 'usa',
    label: 'Mandat 2 - Projet USA',
    context:
      "Mandat inspire du document Generation Holding SA: analyser le marche des generiques dermatologiques, evaluer le projet USA sous l angle financier et risques, puis formaliser une recommandation exploitable.",
    objectives: [
      'Structurer la data room du mandat et clarifier les hypotheses.',
      'Comparer le groupe sur plusieurs exercices pour mesurer la capacite de financement.',
      'Mesurer le potentiel de marche accessible pour les generiques dermatologiques.',
      'Modeliser le projet USA en scenarios et suivre la creation de valeur.',
      'Centraliser les risques et les actions de mitigation.',
    ],
    deliverables: [
      'Note de cadrage du mandat',
      'Synthese de marche',
      'Modele financier par scenarios',
      'Registre des risques',
      'Memo executif go / no-go',
    ],
    checklist: [
      {
        id: 'market-data',
        title: 'Verifier les hypotheses de taille de marche',
        owner: 'Strategy',
        done: true,
      },
      {
        id: 'regulatory',
        title: 'Confirmer le calendrier reglementaire FDA',
        owner: 'Regulatory',
        done: false,
      },
      {
        id: 'pricing',
        title: 'Valider la strategie de prix et les remises',
        owner: 'Commercial',
        done: false,
      },
      {
        id: 'funding',
        title: 'Confirmer le plafond de financement acceptable',
        owner: 'Finance',
        done: true,
      },
    ],
    company: {
      ...defaultCompany,
    },
    latestYear: 2025,
    yearCount: 2,
    historicalInputs: {
      ...defaultHistoricalInputs,
      2025: {
        ...defaultInputs,
        revenue: 382,
        purchases: 181,
        personnelExpenses: 83,
        otherOperatingExpenses: 49,
        depreciation: 19,
        financialResult: -4,
        taxExpense: 7,
        nonRecurringItems: 3,
        inventory: 112,
        receivables: 118,
        cash: 34,
        fixedAssets: 148,
        equity: 163,
        longTermDebt: 74,
        shortTermFinancialDebt: 28,
        suppliers: 58,
        otherOperatingLiabilities: 44,
        previousBfr: 96,
        openingCash: 22,
        capex: 24,
        assetDisposals: 0,
        newLongTermDebt: 18,
        debtRepayment: 9,
        capitalIncrease: 0,
        dividends: 5,
        latentReserves: 0,
        otherNonCashAdjustments: 2,
      },
      2024: {
        ...defaultHistoricalInputs[2024],
        revenue: 341,
        purchases: 158,
        personnelExpenses: 79,
        otherOperatingExpenses: 43,
        depreciation: 17,
        financialResult: -3,
        taxExpense: 4,
        nonRecurringItems: 1,
        inventory: 96,
        receivables: 101,
        cash: 22,
        fixedAssets: 136,
        equity: 148,
        longTermDebt: 69,
        shortTermFinancialDebt: 24,
        suppliers: 53,
        otherOperatingLiabilities: 39,
        previousBfr: 88,
        openingCash: 16,
        capex: 21,
        assetDisposals: 0,
        newLongTermDebt: 11,
        debtRepayment: 7,
        capitalIncrease: 0,
        dividends: 4,
        latentReserves: 0,
        otherNonCashAdjustments: 1,
      },
    },
    marketInputs: {
      totalMarketSize: 820000,
      dermatologyShare: 9,
      genericShare: 34,
      marketGrowthRate: 6,
      addressableShare: 42,
      targetShare: 3.2,
      averagePricePerTreatment: 38,
      competitorCount: 8,
      regulatoryLeadMonths: 15,
    },
    projectInputs: {
      projectName: 'USA',
      currency: 'USD',
      discountRate: 11,
      taxRate: 21,
      workingCapitalRate: 18,
      initialWorkingCapital: 600,
      timeToMarketMonths: 12,
      decisionDeadline: 'Q3 2026',
      sponsor: 'Direction financiere groupe',
      years: ['2026', '2027', '2028', '2029', '2030'],
      revenueByYear: {
        2026: 4200,
        2027: 7600,
        2028: 11000,
        2029: 13800,
        2030: 15500,
      },
      ebitdaMarginByYear: {
        2026: 8,
        2027: 14,
        2028: 18,
        2029: 21,
        2030: 22,
      },
      capexByYear: {
        2026: 3500,
        2027: 2200,
        2028: 900,
        2029: 700,
        2030: 650,
      },
      depreciationByYear: {
        2026: 500,
        2027: 860,
        2028: 980,
        2029: 940,
        2030: 880,
      },
      fixedCostsByYear: {
        2026: 900,
        2027: 1050,
        2028: 1240,
        2029: 1310,
        2030: 1360,
      },
    },
    scenarios: {
      base: {
        label: 'Base',
        revenueMultiplier: 1,
        marginMultiplier: 1,
        opexMultiplier: 1,
        capexMultiplier: 1,
        workingCapitalMultiplier: 1,
      },
      upside: {
        label: 'Upside',
        revenueMultiplier: 1.14,
        marginMultiplier: 1.06,
        opexMultiplier: 1.03,
        capexMultiplier: 1.04,
        workingCapitalMultiplier: 1.02,
      },
      downside: {
        label: 'Downside',
        revenueMultiplier: 0.81,
        marginMultiplier: 0.92,
        opexMultiplier: 1.07,
        capexMultiplier: 1.08,
        workingCapitalMultiplier: 1.1,
      },
    },
    riskRegister: [
      {
        id: 'regulatory-approval',
        category: 'Reglementaire',
        title: 'Retard d homologation FDA',
        probability: 4,
        impact: 5,
        owner: 'Regulatory',
        mitigation: 'Planifier un buffer de calendrier et un pre-audit qualite.',
      },
      {
        id: 'pricing-pressure',
        category: 'Commercial',
        title: 'Pression prix plus forte que prevu',
        probability: 4,
        impact: 4,
        owner: 'Commercial',
        mitigation: 'Construire une grille de prix plancher et differencier les canaux.',
      },
      {
        id: 'supply-chain',
        category: 'Operations',
        title: 'Ruptures ou dependance fournisseur',
        probability: 3,
        impact: 4,
        owner: 'Operations',
        mitigation: 'Qualifier une deuxieme source et securiser les MOQ.',
      },
      {
        id: 'working-capital',
        category: 'Finance',
        title: 'Derive du BFR a cause des conditions clients',
        probability: 3,
        impact: 4,
        owner: 'Finance',
        mitigation: 'Encadrer les remises et imposer un suivi mensuel DSO / stocks.',
      },
      {
        id: 'execution',
        category: 'Execution',
        title: 'Sous-dimensionnement de l equipe locale',
        probability: 2,
        impact: 3,
        owner: 'PMO',
        mitigation: 'Sequencer la montee en charge par lots et points de passage.',
      },
    ],
  },
];
